server:
  port: 10001
spring:
  application:
    name: InfoInService
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/

kafka:
  consumer:
    zookeeper:
      connect: hadoop102:2181
    servers: hadoop102:9092
    enable:
      auto:
        commit: true
    session:
      timeout: 6000
    auto:
      commit:
        interval: 100
      offset:
        reset: latest
    topic: test
    group:
      id: test
    concurrency: 10

  producer:
    servers: hadoop102:9092
    retries: 0
    batch:
      size: 4096
    linger: 1
    buffer:
      memory: 40960